blueprint:
  name: Inovelli Blue Series Notification (ZHA)
  description: >-
    A script that sends an LED bar notification to an Inovelli Blue Series device (VZM31-SN, VZM35-SN).
  domain: script
  input:
    notification_device:
      name: Device
      description: Device to send the notification to.
      selector:
        device:
          integration: zha
          manufacturer: Inovelli
    LEDEffectType:
      name: LED Effect Type
      description: "0: Off, 1: Solid, 2: Fast Blink, 3: Slow Blink, 4: Pulse, 5: Chase, 6: Open/Close, 7: Small to Big, 255: Clear"
      selector:
        number:
          min: 0
          max: 255
    LEDEffectColor:
      name: LED Effect Color
      description: "0:-254: Hue based on Color Wheel, 255: White"
      selector:
        rgb_color:
    LEDEffectLevel:
      name: LED Effect Level
      description: "0-100% Brightness Level"
      selector:
        number:
          min: 0
          max: 100
    LEDEffectDuration:
      name: LED Effect Duration
      description: "1-60: Duration in seconds, 61-120: Duration in minutes (minus 60), 120-254: Duration in hours (minus 120), 255: Indefinite duration"
      selector:
        number:
          min: 0
          max: 255
variables:
  device_str: !input notification_device
  device_ieee: "{{ (device_attr((device_str), 'identifiers')|list).0.1 }}"
  max_channel: "{{ max(LEDEffectColor[0],LEDEffectColor[1],LEDEffectColor[2]) }}"
  min_channel: "{{ max(LEDEffectColor[0],LEDEffectColor[1],LEDEffectColor[2]) }}"
  hue: >
    {% if max_channel == LEDEffectColor[0] %}
      {{ (LEDEffectColor[1] - LEDEffectColor[2] / (max_channel - min_channel)) * 60 }}
    {% elseif max_channel == LEDEffectColor[1] %}
      {{ (2 + (LEDEffectColor[2] - LEDEffectColor[0] / (max_channel - min_channel))) * 60 }}
    {% else %}
      {{ (4 + (LEDEffectColor[0] - LEDEffectColor[2] / (max_channel - min_channel)) * 60 }}
    {% endif %}
  hue_final: >
    {% if hue < 0 %}
      {{ round(hue + 360) }}
    {% else %}
      {{ round(hue) }}
    {% endif %}
mode: single
sequence:
  - service: zha.issue_zigbee_cluster_command
    data:
      ieee: "{{ device_ieee }}"
      endpoint_id: 1
      cluster_id: 64561
      cluster_type: in
      command: 1
      command_type: server
      args:
        - !input LEDEffectType
        - {{ hue_final }}
        - !input LEDEffectLevel
        - !input LEDEffectDuration
      manufacturer: "4655"
